services:
type: web
name: klassenraumchat
runtime: python
pythonVersion: "3.11"  # oder "3.12"
buildCommand: pip install -r requirements.txt
startCommand: gunicorn --bind 0.0.0.0:$PORT --worker-class gevent -w 1 app:app
envVars:
key: FLASK_ENV
value: production




